[[ODEInterface]]
arch = "aarch64"
git-tree-sha1 = "61ef36f241d72f288bb53e21db9d80e03555f055"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "02c57569b23cf6c354560388e32e3f48863e4b644e9c65350207185cbb14d9c2"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[ODEInterface]]
arch = "aarch64"
git-tree-sha1 = "af523ab250df37b370f39525501a37665a561b84"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "92a8d3ebc5867c7fd304a75875c6fe3616632980038ae5a0718546c694dfe5be"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[ODEInterface]]
arch = "aarch64"
git-tree-sha1 = "b23d8419af758558def43ce33018f8959a11c699"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "12a71ea6cc962aa0311a79840bebbb5a735323de5f1a463644e8b44d6d88c2da"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[ODEInterface]]
arch = "aarch64"
git-tree-sha1 = "97eeb5d971e448f28be19c0f7adcf22e12fe8f17"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "49b9b02955bb9ca02184d2c97d7548f84c241b9f1e6ea7432e43d80a3917f9aa"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[ODEInterface]]
arch = "aarch64"
git-tree-sha1 = "4576067324bcd6e033d598b77ff2933751b27ce1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "4d251756fcbbb8281438718966030ee9e37bcf8f99b8947aaba34512f079d5da"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[ODEInterface]]
arch = "aarch64"
git-tree-sha1 = "aca579df5c0311f8bca05ea4a5851691a2f9c2e0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "b4e3f9ff11ee1792b64d93735b5aa2155c0ca377c1198317c23b7f342dd78a86"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[ODEInterface]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6eef0d5e8f9b0ecec2a14d89273a821723ac08f0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "ba2e97ba29fe5567661d273f5d3df9d8234b76a53c14a89dea9d27bbd06df16e"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[ODEInterface]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7c4d709a0102b25b9563b9a9e5d63aa3e660e6da"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "9e07bc83c14aa0bb70fbac1f5b08444abf5cbd18293149dec7fc4b721fb49553"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[ODEInterface]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cee284a474bb554234c3c740b32d1cd3a125655e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "ccfe9554250272bfca396fa51822c705a2292e8a7b8cbb14dd766383994353b4"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[ODEInterface]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "43f37376c3f6682ba48c5e8c828f9e9692f658db"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "21c7ed8c292dc90334ef5fbdf38e9d12ef1e9d87ab744649ea2df90aca88c936"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[ODEInterface]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3a10afb29c8ecacccf765b681a6ca353e46dcc2e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "d1c769e4f423937dbc210d467c73ac88cb293a15f9e939ed36364212752ddc2d"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[ODEInterface]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3f58fd2098a938107f9e059ab3677da9abe68da4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "05266340c0ca31c29292f7a5a0021430f0fb2864f501e862880bb157d152afcb"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[ODEInterface]]
arch = "i686"
git-tree-sha1 = "cd7957b13c40d32cb3ab88b6e6577295f611abca"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "b407425b97a5747d1d493eb4750b8ea11084dac13911943fc6fbd1d3fbf83c33"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.i686-linux-gnu-libgfortran3.tar.gz"
[[ODEInterface]]
arch = "i686"
git-tree-sha1 = "d517637d9f78b25d8722914a8da88889110d7f8f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "aa6b2578b2b6cb8df8ab49e997f5251146596c5971bde2a4d3ade3e4646cb6c6"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.i686-linux-gnu-libgfortran4.tar.gz"
[[ODEInterface]]
arch = "i686"
git-tree-sha1 = "aeafaf544ae739d2839122c063431ee638976167"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "c5865beba859c18372efa4d3a53c95b3e20246f17d647344cd835242c5fba9f0"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.i686-linux-gnu-libgfortran5.tar.gz"
[[ODEInterface]]
arch = "i686"
git-tree-sha1 = "d7c638e34e3d748a465583787f6919c89cba7738"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "fd2f73bbbfc1358e435e5553c24ee665c4e3960d74fd98fc4a99a3a0dd88cc57"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.i686-linux-musl-libgfortran3.tar.gz"
[[ODEInterface]]
arch = "i686"
git-tree-sha1 = "13ca6205d066ab3b961b60ad60200bdb8b2f34aa"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "7bddca85240f4aa3615ca94d77c54ee7169903cd3401efa2819dee6a677777c6"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.i686-linux-musl-libgfortran4.tar.gz"
[[ODEInterface]]
arch = "i686"
git-tree-sha1 = "65532f199ac3ef7c4707423b595862d51f75a016"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "ae96510a560f2e241d5a67350041ec101cb6296fe3601a3a1e9a259b37df86cd"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.i686-linux-musl-libgfortran5.tar.gz"
[[ODEInterface]]
arch = "i686"
git-tree-sha1 = "5b354cef3e5aa54a9987d1cedc976ae933d27d78"
libgfortran_version = "3.0.0"
os = "windows"

    [[ODEInterface.download]]
    sha256 = "a1962fdb9276b92352f8b264844a3d0fd54d32ba61f51f365bd991810f35d517"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[ODEInterface]]
arch = "i686"
git-tree-sha1 = "630aef63c2be42cdc015db3f0da715f1911370d8"
libgfortran_version = "4.0.0"
os = "windows"

    [[ODEInterface.download]]
    sha256 = "d9f2f5956e75a7d8b5cf84deb3fe25ac106435b4cd7daaf51a32440d343fce39"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[ODEInterface]]
arch = "i686"
git-tree-sha1 = "214a986c2cc25267365b458162aba556d85650e3"
libgfortran_version = "5.0.0"
os = "windows"

    [[ODEInterface.download]]
    sha256 = "17047085a12ed48a676d95c194162178d0ea1e9e853872923b47014b892a6c1e"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[ODEInterface]]
arch = "powerpc64le"
git-tree-sha1 = "ec898e5c7293bd4ef67004ee2d297b63b178204f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "47ef14b4295d8fcc2ba4f3d9bf30c8b745dc74e02b5f533a696f41a24aaabaf0"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[ODEInterface]]
arch = "powerpc64le"
git-tree-sha1 = "ae27658a96fef5d95f0fb8c416ecb9b71408092a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "81c30d6159bdff5d13a92c595b69f2df22873119d2436dcb421ba04fcee9e250"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[ODEInterface]]
arch = "powerpc64le"
git-tree-sha1 = "b8ef0d46efe920e77c2d622d7dcaf9534e5d6665"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "334624d8372edab4c1a8e60ccb5b0ee1bf07ac834499f2df06dc8983410e9dba"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[ODEInterface]]
arch = "x86_64"
git-tree-sha1 = "d73997c7b9d1130c072f890b3d2fe168e82064c7"
libgfortran_version = "3.0.0"
os = "macos"

    [[ODEInterface.download]]
    sha256 = "4fb4bf320ed478ad25b5de78bb99c64d02c63da3a51538e7d4047da9df74745f"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[ODEInterface]]
arch = "x86_64"
git-tree-sha1 = "e09351362618f2be98dfb7e4623f318d0f777a5a"
libgfortran_version = "4.0.0"
os = "macos"

    [[ODEInterface.download]]
    sha256 = "8b034441541bfdd7eb98dcd28f96e5905fa8545f26199ed179ba1864fc8b0a8c"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[ODEInterface]]
arch = "x86_64"
git-tree-sha1 = "cb4557fa4c527ab46b4e33f6d2bee8f547910060"
libgfortran_version = "5.0.0"
os = "macos"

    [[ODEInterface.download]]
    sha256 = "36bab9944254de042c3014fbaef1ce43c905bce4f75363ea9ef3ff05a45a0c17"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[ODEInterface]]
arch = "x86_64"
git-tree-sha1 = "805cce79aa865e273ff208e7c0c3d10b2d857b95"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "40b03d878c043f1003ddfe6de2fa5edd95b64088a91e4bf612baf9baa9799017"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[ODEInterface]]
arch = "x86_64"
git-tree-sha1 = "e0f24537ac954f07d5a5be26f848925fa5cbf605"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "41b22c5b70a790c83010c6393ed4643d7001c669132c6b43cfa1be3e35778fa8"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[ODEInterface]]
arch = "x86_64"
git-tree-sha1 = "7c6ecee5eb3d7c5e189426fb859547773b34325f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "c3f0165f34929583f6361ae2dc979f34c547309cf7f7fce46f14b1af0bf6efd1"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[ODEInterface]]
arch = "x86_64"
git-tree-sha1 = "3f23bf3bf507c100ebd6242e89299d6bad3c6502"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "3ed7ddcce67de4fd64e14a5e78c7981112441897546ab8eb400f7e5889e11492"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[ODEInterface]]
arch = "x86_64"
git-tree-sha1 = "4bc21cbf1cf9690d0c2995b1a8ac6afa4080cdd6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "ee75241fd48adec0ac4783720d001439a7fb746813eb62fac295ca3cad124896"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[ODEInterface]]
arch = "x86_64"
git-tree-sha1 = "77de0257cf37b41805586aa6ae3a9531c31a73de"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ODEInterface.download]]
    sha256 = "ee9b3b07ec2a27370baae507b31a0e2a91ce21c2d2bc6a04b3c9c37d6aa093ee"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[ODEInterface]]
arch = "x86_64"
git-tree-sha1 = "04acf883589f32296908fbbc9b542ce43b7ee350"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[ODEInterface.download]]
    sha256 = "b6a7a012e89603b37a61266d3bf697c782c622aa82522dba22fa0973174f37ab"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[ODEInterface]]
arch = "x86_64"
git-tree-sha1 = "a322e67d0c383fa1006f26230f19b3cf52e3032e"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[ODEInterface.download]]
    sha256 = "c135d6141b2e24d69cafd350e5cc860182fc993e35e1c02e7b95443ef59dc29c"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[ODEInterface]]
arch = "x86_64"
git-tree-sha1 = "13173a715e99f9713381fce6f3e0a2a48c9d4a51"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[ODEInterface.download]]
    sha256 = "df4f15b0069cbc67368ecaeba5dec0b6cca24c4f208391c2c426ff5554cd89dc"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[ODEInterface]]
arch = "x86_64"
git-tree-sha1 = "1a0313e218c63fc1c04f6f26184cf3823c8c7ef9"
libgfortran_version = "3.0.0"
os = "windows"

    [[ODEInterface.download]]
    sha256 = "351056c9e835d92fb85fd381e6471b7b25a336f59743fc196bb8594448479017"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[ODEInterface]]
arch = "x86_64"
git-tree-sha1 = "4c7681c8fedcac9ef3c4ddaaccab410292d34b66"
libgfortran_version = "4.0.0"
os = "windows"

    [[ODEInterface.download]]
    sha256 = "27568f885d43cbfd53fe72e4b230bc76aedbc386c3b3ea09f32fc7d6cb055911"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[ODEInterface]]
arch = "x86_64"
git-tree-sha1 = "7ba02acb250a3e00e7c029856911ba3b76e80359"
libgfortran_version = "5.0.0"
os = "windows"

    [[ODEInterface.download]]
    sha256 = "5a9ffb3d350f889144da25e6afdf1a56499f861d16fb0fdf8772723fad5cbeb7"
    url = "https://github.com/JuliaBinaryWrappers/ODEInterface_jll.jl/releases/download/ODEInterface-v0.0.1+0/ODEInterface.v0.0.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
