# Autogenerated wrapper script for ODEInterface_jll for armv7l-linux-musleabihf-libgfortran5
export libbvp_m_proxy, libbvpsol, libbvpsol_i32, libcolnew, libcolnew_i32, libddeabm, libddeabm_i32, libddebdf, libddebdf_i32, libdop853, libdop853_i32, libdopri5, libdopri5_i32, libodex, libodex_i32, libradau, libradau5, libradau5_i32, libradau_i32, librodas, librodas_i32, libseulex, libseulex_i32

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("ODEInterface")
JLLWrappers.@declare_library_product(libbvp_m_proxy, "bvp_m_proxy.so")
JLLWrappers.@declare_library_product(libbvpsol, "bvpsol.so")
JLLWrappers.@declare_library_product(libbvpsol_i32, "bvpsol_i32.so")
JLLWrappers.@declare_library_product(libcolnew, "colnew.so")
JLLWrappers.@declare_library_product(libcolnew_i32, "colnew_i32.so")
JLLWrappers.@declare_library_product(libddeabm, "ddeabm.so")
JLLWrappers.@declare_library_product(libddeabm_i32, "ddeabm_i32.so")
JLLWrappers.@declare_library_product(libddebdf, "ddebdf.so")
JLLWrappers.@declare_library_product(libddebdf_i32, "ddebdf_i32.so")
JLLWrappers.@declare_library_product(libdop853, "dop853.so")
JLLWrappers.@declare_library_product(libdop853_i32, "dop853_i32.so")
JLLWrappers.@declare_library_product(libdopri5, "dopri5.so")
JLLWrappers.@declare_library_product(libdopri5_i32, "dopri5_i32.so")
JLLWrappers.@declare_library_product(libodex, "odex.so")
JLLWrappers.@declare_library_product(libodex_i32, "odex_i32.so")
JLLWrappers.@declare_library_product(libradau, "radau.so")
JLLWrappers.@declare_library_product(libradau5, "radau5.so")
JLLWrappers.@declare_library_product(libradau5_i32, "radau5_i32.so")
JLLWrappers.@declare_library_product(libradau_i32, "radau_i32.so")
JLLWrappers.@declare_library_product(librodas, "rodas.so")
JLLWrappers.@declare_library_product(librodas_i32, "rodas_i32.so")
JLLWrappers.@declare_library_product(libseulex, "seulex.so")
JLLWrappers.@declare_library_product(libseulex_i32, "seulex_i32.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libbvp_m_proxy,
        "lib/bvp_m_proxy.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libbvpsol,
        "lib/bvpsol.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libbvpsol_i32,
        "lib/bvpsol_i32.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcolnew,
        "lib/colnew.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcolnew_i32,
        "lib/colnew_i32.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libddeabm,
        "lib/ddeabm.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libddeabm_i32,
        "lib/ddeabm_i32.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libddebdf,
        "lib/ddebdf.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libddebdf_i32,
        "lib/ddebdf_i32.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libdop853,
        "lib/dop853.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libdop853_i32,
        "lib/dop853_i32.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libdopri5,
        "lib/dopri5.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libdopri5_i32,
        "lib/dopri5_i32.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libodex,
        "lib/odex.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libodex_i32,
        "lib/odex_i32.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libradau,
        "lib/radau.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libradau5,
        "lib/radau5.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libradau5_i32,
        "lib/radau5_i32.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libradau_i32,
        "lib/radau_i32.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        librodas,
        "lib/rodas.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        librodas_i32,
        "lib/rodas_i32.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libseulex,
        "lib/seulex.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libseulex_i32,
        "lib/seulex_i32.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
