# Autogenerated wrapper script for ODEInterface_jll for x86_64-w64-mingw32-libgfortran3
export libbvp_m_proxy, libbvpsol, libbvpsol_i32, libcolnew, libcolnew_i32, libddeabm, libddeabm_i32, libddebdf, libddebdf_i32, libdop853, libdop853_i32, libdopri5, libdopri5_i32, libodex, libodex_i32, libradau, libradau5, libradau5_i32, libradau_i32, librodas, librodas_i32, libseulex, libseulex_i32

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("ODEInterface")
JLLWrappers.@declare_library_product(libbvp_m_proxy, "bvp_m_proxy.dll")
JLLWrappers.@declare_library_product(libbvpsol, "bvpsol.dll")
JLLWrappers.@declare_library_product(libbvpsol_i32, "bvpsol_i32.dll")
JLLWrappers.@declare_library_product(libcolnew, "colnew.dll")
JLLWrappers.@declare_library_product(libcolnew_i32, "colnew_i32.dll")
JLLWrappers.@declare_library_product(libddeabm, "ddeabm.dll")
JLLWrappers.@declare_library_product(libddeabm_i32, "ddeabm_i32.dll")
JLLWrappers.@declare_library_product(libddebdf, "ddebdf.dll")
JLLWrappers.@declare_library_product(libddebdf_i32, "ddebdf_i32.dll")
JLLWrappers.@declare_library_product(libdop853, "dop853.dll")
JLLWrappers.@declare_library_product(libdop853_i32, "dop853_i32.dll")
JLLWrappers.@declare_library_product(libdopri5, "dopri5.dll")
JLLWrappers.@declare_library_product(libdopri5_i32, "dopri5_i32.dll")
JLLWrappers.@declare_library_product(libodex, "odex.dll")
JLLWrappers.@declare_library_product(libodex_i32, "odex_i32.dll")
JLLWrappers.@declare_library_product(libradau, "radau.dll")
JLLWrappers.@declare_library_product(libradau5, "radau5.dll")
JLLWrappers.@declare_library_product(libradau5_i32, "radau5_i32.dll")
JLLWrappers.@declare_library_product(libradau_i32, "radau_i32.dll")
JLLWrappers.@declare_library_product(librodas, "rodas.dll")
JLLWrappers.@declare_library_product(librodas_i32, "rodas_i32.dll")
JLLWrappers.@declare_library_product(libseulex, "seulex.dll")
JLLWrappers.@declare_library_product(libseulex_i32, "seulex_i32.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libbvp_m_proxy,
        "bin\\bvp_m_proxy.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libbvpsol,
        "bin\\bvpsol.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libbvpsol_i32,
        "bin\\bvpsol_i32.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcolnew,
        "bin\\colnew.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcolnew_i32,
        "bin\\colnew_i32.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libddeabm,
        "bin\\ddeabm.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libddeabm_i32,
        "bin\\ddeabm_i32.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libddebdf,
        "bin\\ddebdf.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libddebdf_i32,
        "bin\\ddebdf_i32.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libdop853,
        "bin\\dop853.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libdop853_i32,
        "bin\\dop853_i32.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libdopri5,
        "bin\\dopri5.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libdopri5_i32,
        "bin\\dopri5_i32.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libodex,
        "bin\\odex.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libodex_i32,
        "bin\\odex_i32.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libradau,
        "bin\\radau.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libradau5,
        "bin\\radau5.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libradau5_i32,
        "bin\\radau5_i32.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libradau_i32,
        "bin\\radau_i32.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        librodas,
        "bin\\rodas.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        librodas_i32,
        "bin\\rodas_i32.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libseulex,
        "bin\\seulex.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libseulex_i32,
        "bin\\seulex_i32.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
